project:
  type: website
  title: "Selected Chapters"
  output-dir: ../_site

website:
  page-footer:
    center: "Copyright © 2026 University of Geneva"
  navbar:
    search: true
    right:
      - text: Language
        icon: globe
        menu:
          - text: "English"
            href: index.html
          - text: "French"
            href: fr/index.html

  sidebar:
    style: docked
    search: true
    
    contents:
      - section: "Course"
        contents:
          - section: "Introduction"
            contents:
              - text: "Details"
                href: ch1.qmd
              - text: "Summary"
                href: ch1r.qmd
              - text: "Quiz"
                href: ch1q.qmd
          - section: "Foundations"
            contents:
              - text: "Details"
                href: ch2.qmd
              - text: "Summary"
                href: ch2r.qmd
              - text: "Quiz"
                href: ch2q.qmd
          - section: "Properties"
            contents:
              - text: "Details"
                href: ch3.qmd
              - text: "Summary"
                href: ch3r.qmd
              - text: "Quiz"
                href: ch3q.qmd
          - section: "Applications"
            contents:
              - text: "Details"
                href: ch4.qmd
              - text: "Summary"
                href: ch4r.qmd
              - text: "Quiz"
                href: ch4q.qmd
          - section: "Error Correction"
            contents:
              - text: "Details"
                href: ch5.qmd
              - text: "Summary"
                href: ch5r.qmd
              - text: "Quiz"
                href: ch5q.qmd

      - section: "Exam"
        contents:
          - text: "Details"
            href: exam_answers.qmd
          - text: "Summary"
            href: exam_syntheses.qmd
          - text: "Quiz"
            href: exam_quiz.qmd


format:
  html:
    theme:
      dark: ../macchiato.scss
      light: ../latte.scss
    toc: true
    embed-resources: true

# filters:
#   - diagram
