project:
  type: website
  title: "Selected Chapters"
  output-dir: ../_site

website:
  page-footer:
    center: "Copyright © 2026 University of Geneva"
  navbar:
    search: true
    right:
      - text: Language
        icon: globe
        menu:
          - text: "English"
            href: index.html
          - text: "French"
            href: fr/index.html
