project:
  type: website
  title: "Selected Chapters"
  output-dir: ../_site/fr

website:
  # Language switching setup

  navbar:
    # background: primary
    search: true
    # Right side for language selector
    right:
      - text: Langage
        icon: globe
        menu:
          - text: "Anglais"
            href: ../index.html
          - text: "Français"
            href: index.html

  sidebar:
    style: docked
    search: true
    
    contents:
      - section: "Cours"
        contents:
          - section: "Quantum computing"
            contents:
              - section: "Details"
                contents: ch1c.qmd
              - ch1.qmd
              - section: "Synthese"
                contents: ch1r.qmd


format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    embed-resources: true
  # pdf:
  #   toc: true
  # docx:
  #   toc: true

# filters:
#   - diagram
