project:
  type: website
  title: "Selected Chapters"
  output-dir: ../_site/fr

website:
  page-footer:
    center: "Copyright © 2026 University of Geneva"
  navbar:
    search: true
    right:
      - text: Langage
        icon: globe
        menu:
          - text: "Anglais"
            href: ../index.html
          - text: "Français"
            href: index.html

  sidebar:
    style: docked
    search: true
    
    contents:
      - section: "Cours"
        contents:
          - section: "Introduction"
            contents:
              - text: "Détails"
                href: ch1.qmd
              - text: "Synthèse"
                href: ch1r.qmd
              - text: "Quiz"
                href: ch1q.qmd
          - section: "Fondements"
            contents:
              - text: "Détails"
                href: ch2.qmd
              - text: "Synthèse"
                href: ch2r.qmd
              - text: "Quiz"
                href: ch2q.qmd
          - section: "Propriétés"
            contents:
              - text: "Détails"
                href: ch3.qmd
              - text: "Synthèse"
                href: ch3r.qmd
              - text: "Quiz"
                href: ch3q.qmd
          - section: "Applications"
            contents:
              - text: "Détails"
                href: ch4.qmd
              - text: "Synthèse"
                href: ch4r.qmd
              - text: "Quiz"
                href: ch4q.qmd
          - section: "Correction d'erreurs"
            contents:
              - text: "Détails"
                href: ch5.qmd
              - text: "Synthèse"
                href: ch5r.qmd
              - text: "Quiz"
                href: ch5q.qmd
      - section: "Examen"
        contents:
          - text: "Détails"
            href: exam_answers.qmd
          - text: "Synthèse"
            href: exam_syntheses.qmd
          - text: "Quiz"
            href: exam_quiz.qmd


format:
  html:
    theme:
      dark: ../macchiato.scss
      light: ../latte.scss
    toc: true
    embed-resources: true
